version: '3'

tasks:
  phpstan:
    cmds:
      - vendor/bin/phpstan analyse -c phpstan.neon --memory-limit 1G

  rector:
    cmds:
      - vendor/bin/rector --dry-run

  ccs:
    cmds:
      - vendor/bin/pint --config pint.json -v --test

  test:
    cmds:
      - php artisan test {{.CLI_ARGS}}

  ci:
    cmds:
      - task: rector
      - task: phpstan
      - task: ccs
      - task: test

  fix:rector:
    cmds:
      - vendor/bin/rector

  fix:ccs:
    cmds:
      - vendor/bin/pint --config pint.json

  fix:
    cmds:
      - task: fix:rector
      - task: fix:ccs
